from restrictedstopwatch import RestrictedStopwatch

sw = RestrictedStopwatch(3)
print("Starting 1")
sw.start()
print("Stopping 1")
sw.stop()
print("Starting 2")
sw.start()
print("Stopping 2")
sw.stop()
print("Starting 3")
sw.start()
print("Stopping 3")
sw.stop()
print("Starting 4")
sw.start()
print("Stopping 4")
sw.stop()
print("Done")
